pom.xml
src/main/scala/com/dmetasoul/lakesoul/tables/LakeSoulTable.scala
src/main/scala/org/apache/spark/sql/lakesoul/LakeSoulUtils.scala
src/main/scala/org/apache/spark/sql/lakesoul/TransactionCommit.scala
src/main/scala/org/apache/spark/sql/lakesoul/commands/CreateTableCommand.scala
src/main/scala/org/apache/spark/sql/lakesoul/commands/WriteIntoTable.scala
src/main/scala/org/apache/spark/sql/lakesoul/sources/LakeSoulDataSource.scala
src/main/scala/org/apache/spark/sql/lakesoul/utils/MetaData.scala
src/test/scala/org/apache/spark/sql/lakesoul/TableCreationTests.scala
src/test/scala/org/apache/spark/sql/lakesoul/commands/AlterTableTests.scala

This patch adds a table property 'lakesoul_cdc_change_column' to identify a change kind column in one LakeSoul table.
This column should be of type string and could only contain values in one of ('update', 'delete', 'insert'). This allows LakeSoul table to represent a continuous change status according to upstream changing data. And LakeSoul is able to accept different kinds of CDC sources including Debezium, Canal and Flink CDC.
1. Allow `create table` and `alter table` to set TBLPROPERTIES with key 'lakesoul_cdc_change_column'
2. Fix the case when using DataFrame API or TableCreator API to create table but table options were incorrectly ignored
1. Add test cases including table creation with property via SQL, DataFrame and TableCreator API
2. Add test case for alter table DDL

CDC support v1: add table property to identify change kind column

---

pom.xml
src/main/scala/com/dmetasoul/lakesoul/meta/DataOperation.scala
src/main/scala/com/dmetasoul/lakesoul/sql/LakeSoulSparkSessionExtension.scala
src/main/scala/org/apache/spark/sql/lakesoul/TransactionCommit.scala
src/main/scala/org/apache/spark/sql/lakesoul/catalog/LakeSoulCatalog.scala
src/main/scala/org/apache/spark/sql/lakesoul/catalog/LakeSoulScanBuilder.scala
src/main/scala/org/apache/spark/sql/lakesoul/catalog/LakeSoulTableV2.scala
src/main/scala/org/apache/spark/sql/lakesoul/exception/LakeSoulErrors.scala
src/main/scala/org/apache/spark/sql/lakesoul/rules/LakeSoulAnalysis.scala
src/main/scala/org/apache/spark/sql/lakesoul/rules/LakeSoulUnsupportedOperationsCheck.scala
src/main/scala/org/apache/spark/sql/lakesoul/rules/PreprocessTableMergeInto.scala
src/test/scala/org/apache/spark/sql/lakesoul/DataFrameWriterV2Suite.scala
src/test/scala/org/apache/spark/sql/lakesoul/InsertIntoTableSuite.scala
src/test/scala/org/apache/spark/sql/lakesoul/TableCreationTests.scala
src/test/scala/org/apache/spark/sql/lakesoul/commands/MergeIntoSQLSuite.scala
src/test/scala/org/apache/spark/sql/lakesoul/commands/UpdateSuiteBase.scala
src/test/scala/org/apache/spark/sql/lakesoul/commands/UpsertSuiteBase.scala
src/test/scala/org/apache/spark/sql/lakesoul/test/LakeSQLCommandSoulTest.scala

1. Convert MergeInto to Upsert when the following conditions are matched:
1. Merge condition are assignments on all primary key columns
2. No additional conditions in Update/Insert Actions
3. Update expressions are only assignments
1. Currently delete action is not supported. We plan to support delete after cdc feature become stable
2. Add MergeInto test cases
Some known problems:
1. Spark performs analysis for MergeIntoTable logical plan only when no ACCEPT_ANY_SCHEMA presented in table capability. We should only add ACCEPT_ANY_SCHEMA when LakeSoulSQLConf.SCHEMA_AUTO_MIGRATE is enabled. However this causes some behavior change, e.g. some column nullability compatibility checks during dataframe writes would fail:
1. Using Seq to DF method would create nullable schema for StringType, …

support merge into sql when can be converted to upsert

---

src/main/scala/com/dmetasoul/lakesoul/sql/LakeSoulSparkSessionExtension.scala
src/main/scala/org/apache/spark/sql/lakesoul/rules/ProcessCDCTableMergeOnRead.scala
src/test/scala/com/dmetasoul/lakesoul/tables/LakeSoulTableSuite.scala
src/test/scala/org/apache/spark/sql/execution/datasource/ParquetScanSuite.scala
src/test/scala/org/apache/spark/sql/lakesoul/CDCSuite.scala
src/test/scala/org/apache/spark/sql/lakesoul/DDLSuite.scala
src/test/scala/org/apache/spark/sql/lakesoul/DDLUsingPathSuite.scala
src/test/scala/org/apache/spark/sql/lakesoul/DataFrameWriterV2Suite.scala
src/test/scala/org/apache/spark/sql/lakesoul/InsertIntoTableSuite.scala
src/test/scala/org/apache/spark/sql/lakesoul/NotSupportedDDLSuite.scala
src/test/scala/org/apache/spark/sql/lakesoul/TableCreationTests.scala
src/test/scala/org/apache/spark/sql/lakesoul/commands/AlterTableTests.scala
src/test/scala/org/apache/spark/sql/lakesoul/commands/DeleteSQLSuite.scala
src/test/scala/org/apache/spark/sql/lakesoul/commands/DeleteScalaSuite.scala
src/test/scala/org/apache/spark/sql/lakesoul/commands/DeleteSuiteBase.scala
src/test/scala/org/apache/spark/sql/lakesoul/commands/MaterialViewSuite.scala
src/test/scala/org/apache/spark/sql/lakesoul/commands/MergeIntoSQLSuite.scala
src/test/scala/org/apache/spark/sql/lakesoul/commands/UpdateSQLSuite.scala
src/test/scala/org/apache/spark/sql/lakesoul/commands/UpdateScalaSuite.scala
src/test/scala/org/apache/spark/sql/lakesoul/commands/UpdateSuiteBase.scala
src/test/scala/org/apache/spark/sql/lakesoul/commands/UpsertSuiteBase.scala
src/test/scala/org/apache/spark/sql/lakesoul/rules/LakeSoulPostHocAnalysisSuiteSoul.scala
src/test/scala/org/apache/spark/sql/lakesoul/rules/RewriteQueryByMaterialViewBase.scala
src/test/scala/org/apache/spark/sql/lakesoul/schema/CaseSensitivitySuite.scala
src/test/scala/org/apache/spark/sql/lakesoul/schema/SchemaEnforcementSuite.scala
src/test/scala/org/apache/spark/sql/lakesoul/schema/SchemaValidationSuite.scala
src/test/scala/org/apache/spark/sql/lakesoul/test/LakeSoulSQLCommandTest.scala
src/test/scala/org/apache/spark/sql/lakesoul/test/TestUtils.scala

1. Abstract some duplicate beforeEach/afterEach code
2. Avoid some duplicate cases executed.
Fix #1

Optimize duplicate tests and code

---

lakesoul-spark/src/main/scala/org/apache/spark/sql/execution/datasources/v2/merge/MergeParquetScan.scala

fix bug: when bucketId's isSingleFile is false firstly then true, the value MergeFilePartition's isSingleFile should be false

fix MultiPartitionMergeBucketScan bug

---

lakesoul-flink/pom.xml
lakesoul-flink/src/main/java/org/apache/flink/formats/parquet/row/ParquetRowDataWriter.java
lakesoul-flink/src/main/java/org/apache/flink/formats/parquet/utils/ParquetSchemaConverter.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/writer/TableSchemaWriterCreator.java

Close #105 
Currently we hack flink-parquet files to use int64 for timestamp type. In the future we may move these logics to native io layer.

[Flink] write timestamp to int64 instead of int96 in flink sink

---

lakesoul-spark/src/main/scala/com/dmetasoul/lakesoul/meta/MetaVersion.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/catalog/LakeSoulScanBuilder.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/utils/MetaData.scala
lakesoul-spark/src/test/scala/org/apache/spark/sql/execution/datasource/ParquetScanSuite.scala

only one partition and compacted to ParquetScan

Only one partition and compaction to parquet scan

---

.github/workflows/flink-cdc-test.yml
README.md
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/MysqlCdc.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/LakeSoulDDLSink.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/LakeSoulMultiTableSinkStreamBuilder.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/bucket/DefaultMultiTablesBulkFormatBuilder.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/writer/LakeSoulMultiTableSinkWriter.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/types/BinaryDebeziumDeserializationSchema.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/types/BinarySourceRecord.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/types/LakeSoulRecordConvert.java
lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/FlinkCDCMultiTableTest.java
lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/FlinkSerdeTest.java
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/benchmark/Benchmark.scala
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/benchmark/CHBenchmark.scala
script/benchmark/properties

1. Use BinaryRowData+RowType to serialize SourceRecord;
2. Retrieve primary keys in the first place;
3. Compute primary key hash directly from BinaryRowData;
4. Write Update record only once when no partition key fields changed;
5. Tests show about 20%~30% performance improvement in Flink CDC Sink.
Close #116

Flink serde optimization

---

lakesoul-spark/src/main/java/org/apache/spark/sql/execution/datasources/parquet/NativeVectorizedReader.java
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/commands/UpsertSuiteBase.scala

fix unexpectively close partitionColumnVectors on closeCurrentBatch

---

lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/PartitionFilter.scala

when filters is empty, gain full partitionInfo directly to reduce filtering time.

optimize filesForScan

---

native-io/Cargo.lock
native-io/lakesoul-io/Cargo.toml
native-io/lakesoul-io/src/lib.rs

TCMalloc will override malloc/free symbol in the shared lib, which may cause some problem in complex environment.
We may need to find a way to address this.

disable tcmalloc

---

lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/sql/SubmitMain.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/sql/Submitter.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/sql/common/SubmitOption.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/sql/flink/FlinkSqlSubmitter.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/sql/utils/FileUtil.java
lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/SubmitMainTest.java

1. update load flink sql from hdfs in yarn application
2. fix "use default" loaded from zeppelin sql. In zeppelin, "use default" is running well, but in flink sql, "default" is a keyword. So, this update is to replace "use default" to "use `default`" in flink submitter.

update load flink sql from hdfs in yarn application

---

.gitattributes
.github/workflows/native-build.yml

Github has bandwidth limitation on lfs download. Disable git lfs to avoid it.

[Project] disable git lfs

---

lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/DBManager.java
lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/DBUtil.java
lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/DataCommitInfoDao.java
lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/NamespaceDao.java
lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/PartitionInfoDao.java
lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/TableInfoDao.java
lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/TableNameIdDao.java
lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/TablePathIdDao.java
lakesoul-flink/src/main/scala/com/dmetasoul/lakesoul/meta/MetaVersion.scala
lakesoul-spark/src/main/scala/com/dmetasoul/lakesoul/meta/MetaVersion.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/sources/LakeSoulSourceUtils.scala

Refine exception handling in meta layer.
Only exception for primary key conflict in partition_info table would be handled with retry in DBManager.
All other exceptions are thrown.

Fix meta exception handling

---

lakesoul-spark/src/main/scala/com/dmetasoul/lakesoul/tables/LakeSoulTable.scala

partition rollback/cleanup API add timeZoneId, default timeZoneId is null and following with system configuration.

partition rollback/cleanup add timeZoneId

---

lakesoul-flink/pom.xml
lakesoul-spark/pom.xml
native-io/lakesoul-io-java/pom.xml

Arrow-vector depends on jackson-core. Flink doesn't package jackson-core by default (flink-s3-hadoop etc. does). So we package it to avoid class not found issue in local testing scenarios.

[Flink] fix jackson-core package in flink

---

.gitignore
native-metadata/lakesoul-metadata-c/src/lib.rs
python/compile_pb.sh
python/metadata/__init__.py
python/metadata/dao.py
python/metadata/db_manager.py
python/metadata/lib/__init__.py
python/metadata/lib/const.py
python/metadata/lib/lakesoul_metadata_c.py
python/metadata/native_client.py
python/metadata/poc.py
python/metadata/requirement.txt
python/metadata/utils.py

[Python][Native-Metadata] Python interface of lakesoul metadata

---

native-io/lakesoul-io-c/src/lib.rs

[Python] C callback with data

---

lakesoul-flink/pom.xml
lakesoul-spark/src/main/scala/com/dmetasoul/lakesoul/spark/clean/CleanOldCompaction.scala
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/benchmark/Benchmark.scala

Flink cdc 2.4.1 will not capture new sharding table: https://github.com/ververica/flink-cdc-connectors/issues/2306, so rollback to 2.3.0.
This reverts #303 #289

[Flink] rollback flink cdc to 2.3.0 and supplement tables check in benchmark

---

.github/workflows/deployment.yml
.github/workflows/flink-cdc-test.yml
.github/workflows/maven-test.yml
.github/workflows/native-build.yml
lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/jnr/LibLakeSoulMetaData.java
lakesoul-flink/pom.xml
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/MysqlCdc.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/bucket/BulkFormatBuilder.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/bucket/DefaultOneTableBulkFormatBuilder.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/committer/LakeSoulSinkGlobalCommitter.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/writer/AbstractLakeSoulMultiTableSinkWriter.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/writer/LakeSoulMultiTableSinkWriter.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/writer/LakeSoulRowDataOneTableSinkWriter.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/writer/TableSchemaWriterCreator.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/table/LakeSoulTableSink.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/tool/FlinkUtil.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/types/BinarySourceRecordSerializer.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/types/LakeSoulRecordConvert.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/types/LakeSoulRowDataWrapper.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/types/TableSchemaIdentity.java

[Fury](https://github.com/alipay/fury) is an opensourced serialization library using JIT to improve performance.
In LakeSoul's CDC sync job, we need to pass before and after RowData as well as RowType in each record. From Flink's flamegraph we can confirm these objects are causing excessive serde burden.
Using Fury, single core benchmark shows ~80% improvement on end-to-end throughput (numRecordsInPerSecond from 5800 to 10400).

[Flink] Optimize CDC sink serde with Fury

---

lakesoul-common/pom.xml

Idea Intellij may complain 'No scalac found' when building lakesoul-common. So add scala dependencies to avoid this.

add scala in common to address build in idea intellij

---

lakesoul-flink/src/main/java/org/apache/flink/lakesoul/tool/FlinkUtil.java

Ignore class not found exception when there's no hadoop env.

[Flink] Ignore exception when hadoop env missing

---

lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/jnr/NativeUtils.java
lakesoul-spark/src/main/java/org/apache/spark/sql/execution/datasources/parquet/NativeVectorizedReader.java
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/sources/LakeSoulSQLConf.scala
rust/lakesoul-io/src/lakesoul_io_config.rs

turn off native meta query and set prefetch_size=1 for reading large data error

[Bug] turn off native meta query and temporarily disable io prefetch

---

lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/TableInfoDao.java
lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/TablePathIdDao.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/ParquetFilters.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/table/LakeSoulTableSource.java
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/commands/UpsertSuiteBase.scala
rust/lakesoul-io/src/lakesoul_reader.rs

Fix incorrect filter pushdown before merge on read, which may cause incorrect query result.
Part of #284 
Will have a refactor on this issue in near future.

[Bug]filter should not pushdown before merge on read

---

lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/catalog/LakeSoulScanBuilder.scala
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/benchmark/PrimaryKeyFilterEval.scala

- Fix bug when PARQUET_FILTER_PUSHDOWN_ENABLED=false
- Evaluate time cost when PARQUET_FILTER_PUSHDOWN_ENABLED=true/false
- If NATIVE_IO_WRITE_MAX_ROW_GROUP_SIZE is small, time cost of PARQUET_FILTER_PUSHDOWN_ENABLED=true/false are almost equal
- If NATIVE_IO_WRITE_MAX_ROW_GROUP_SIZE is large, case of PARQUET_FILTER_PUSHDOWN_ENABLED=true will use more time than negative case

[Spark]Spark parquet filter pushdown evaluation + bugfix

---

lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/DBManager.java
lakesoul-common/src/main/scala/com/dmetasoul/lakesoul/meta/DataOperation.scala
lakesoul-spark/src/main/scala/com/dmetasoul/lakesoul/spark/clean/CleanExpiredData.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/TransactionalWrite.scala
rust/lakesoul-metadata/src/lib.rs

1. Optimize incremental read: if start timestamp is earliest time of data，reading data from the last version before the end time；
2. Fix compact operation cause column disorder bug and filter rows when cdc column exists and the value is 'delete';
3. Automatically Clean Up Expired Data Task add time zone parameter.

[Spark]optimize incremental read and fix compact operation cause column disorder bug

---

lakesoul-spark/src/main/antlr4/org.apache.spark.sql.catalyst.parser.extensions/LakeSoulSqlExtensions.g4
lakesoul-spark/src/main/scala/com/dmetasoul/lakesoul/sql/LakeSoulSparkSessionExtension.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/LakeSoulSparkSqlExtensionsParser.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/LakeSoulSqlExtensionsAstBuilder.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/LakeSoulSqlExtensionsBasicVisitor.java
lakesoul-spark/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/LakeSoulSqlExtensionsLexer.java
lakesoul-spark/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/LakeSoulSqlExtensionsListener.java
lakesoul-spark/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/LakeSoulSqlExtensionsParser.java
lakesoul-spark/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/LakeSoulSqlExtensionsVisitor.java
lakesoul-spark/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/CallStatement.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/commands/CallExecCommand.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/rules/ProcessCall.scala
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/DDLSuite.scala
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/commands/CompactionSuite.scala
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/commands/RollbackSuite.scala

Spark Sql support call sql syntax for lakesoultable rollback and compaction
For example:
1) usage of call compaction
call LakeSoulTable.compaction(condition=>map('range',1),tablePath=>'file://path/')
call LakeSoulTable.compaction(condition=>map('range',1),tableName=>'lakesoul')
call LakeSoulTable.compaction(tableName=>'lakesoul',hiveTableName=>'hive')
call LakeSoulTable.compaction(tableName=>'lakesoul',cleanOld=>true)
2) usage of call rollback 
call LakeSoulTable.rollback(partitionvalue=>map('range',1),toVersion=>0,tablePath=>'file://path/')
call LakeSoulTable.rollback(partitionvalue=>map('range',1),toVersion=>0,tableName=>'lakesoul')
call LakeSoulTable.rollback(partitionvalue=>map('range',1),toTime=>'2010-01-01 10:00:00',tableName=>'lakesoul')
call …

[Spark] support call sql syntax

---

lakesoul-flink/src/main/java/org/apache/flink/lakesoul/connector/LakeSoulPartitionReader.java
lakesoul-presto/src/main/java/com/facebook/presto/lakesoul/LakeSoulRecordCursor.java
lakesoul-spark/src/main/java/org/apache/spark/sql/execution/datasources/parquet/NativeVectorizedReader.java
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/sources/LakeSoulSQLConf.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/vectorized/GlutenUtils.scala
native-io/lakesoul-io-java/src/main/java/com/dmetasoul/lakesoul/lakesoul/io/NativeIOBase.java
native-io/lakesoul-io-java/src/main/java/com/dmetasoul/lakesoul/lakesoul/io/NativeIOReader.java
native-io/lakesoul-io-java/src/main/java/com/dmetasoul/lakesoul/lakesoul/io/jnr/JnrLoader.java
native-io/lakesoul-io-java/src/main/java/com/dmetasoul/lakesoul/lakesoul/io/jnr/LibLakeSoulIO.java
native-io/lakesoul-io-java/src/main/java/com/dmetasoul/lakesoul/lakesoul/memory/ArrowMemoryUtils.java
native-io/lakesoul-io-java/src/main/scala/com/dmetasoul/lakesoul/LakeSoulArrowReader.scala
native-io/lakesoul-io-java/src/test/scala/com/dmetasoul/lakesoul/TestLakeSoulNativeReaderWriter.scala
rust/lakesoul-io-c/lakesoul_c_bindings.h
rust/lakesoul-io-c/src/lib.rs
rust/lakesoul-io/src/lakesoul_reader.rs

Address some perf issues found during profiling.
1. Table read in Java should use Rust side blocking API to avoid callback overhead in tokio's threads.
2. Reader's schema could be reused after initialization to save some allocations for each batch.
3. Arrow allocator in Java could reserve some memory.

[NativeIO] Use rust block api in file read

---

.gitignore
rust/lakesoul-datafusion/src/lakesoul_table/mod.rs
rust/lakesoul-datafusion/src/test/mod.rs
rust/lakesoul-io/src/helpers.rs
rust/lakesoul-io/src/lakesoul_reader.rs
rust/lakesoul-io/src/lakesoul_writer.rs
rust/lakesoul-io/src/sorted_merge/sort_key_range.rs
rust/lakesoul-io/src/sorted_merge/sorted_stream_merger.rs
rust/lakesoul-io/src/transform.rs

[Rust] Apply clippy and fix typos;

---

lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/LakeSoulRollingPolicyImpl.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/state/LakeSoulMultiTableSinkCommittable.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/writer/LakeSoulWriterBucket.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/writer/NativeParquetWriter.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/table/LakeSoulDynamicTableFactory.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/table/LakeSoulTableSource.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/tool/FlinkUtil.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/tool/LakeSoulSinkOptions.java
rust/lakesoul-io/src/lakesoul_io_config.rs
rust/lakesoul-io/src/lakesoul_reader.rs
rust/lakesoul-io/src/lakesoul_writer.rs
rust/lakesoul-io/src/sorted_merge/sorted_stream_merger.rs
website/docs/03-Usage Docs/06-flink-lakesoul-connector.md
website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/06-flink-lakesoul-connector.md

1. Roll part file for every 5 million rows by default;
2. Fix error not returned when sorting writer failed.

[Flink/Rust] Adjust rolling file logic to reduce memory usage during write

---

lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/Path.java
lakesoul-common/src/main/scala/com/dmetasoul/lakesoul/meta/DataOperation.scala
lakesoul-common/src/main/scala/com/dmetasoul/lakesoul/meta/MetaVersion.scala
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/sql/flink/FlinkSqlSubmitter.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/metadata/LakeSoulCatalog.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/LakeSoulMultiTableSinkStreamBuilder.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/committer/LakeSoulSinkGlobalCommitter.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/LakeSoulOneSplitRecordsReader.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/arrow/LakeSoulArrowSplitRecordsReader.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/tool/LakeSoulKeyGen.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/tool/LakeSoulSinkOptions.java
lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/LakeSoulTestUtils.java
lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/flinkSource/DMLSuite.java
lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/schema/SchemaMigrationTest.java

1. Added a new config AUTO_SCHEMA_CHANGE(lakesoul.sink.auto_schema_change), default false. It is only enabled in `buildLakeSoulDMLSink` and `buildArrowSink` for sink to multiple tables.
2. Set batch size for reader from config BATCH_SIZE

[Flink] Allow disable auto schema change. Add batch size config

---

lakesoul-spark/src/main/scala/com/dmetasoul/lakesoul/spark/clean/CleanExpiredData.scala
lakesoul-spark/src/main/scala/com/dmetasoul/lakesoul/spark/clean/CleanOldCompaction.scala
lakesoul-spark/src/main/scala/com/dmetasoul/lakesoul/spark/clean/CleanUtils.scala
lakesoul-spark/src/main/scala/com/dmetasoul/lakesoul/spark/compaction/CompactionTask.scala
lakesoul-spark/src/main/scala/com/dmetasoul/lakesoul/tables/LakeSoulTable.scala
lakesoul-spark/src/main/scala/com/dmetasoul/lakesoul/tables/execution/LakeSoulTableOperations.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/LakeSoulUtils.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/commands/CompactionCommand.scala
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/commands/CleanOldCompactionSuite.scala

Main work：
1. Automatically clean the previous compaction data after each compaction;
2. When cleaning, directly clean all data before the expiration time, but it is necessary to determine that there is at least one compaction within the unexpired time.

[Spark] Optimization of Compaction Service

---

.github/workflows/consistency-ci.yml
.github/workflows/deployment.yml
.github/workflows/native-build.yml
lakesoul-flink/pom.xml
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/SyncDatabase.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/sql/flink/ExecuteSql.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/sql/flink/FlinkSqlSubmitter.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/sql/flink/LakeSoulInAndOutputJobListener.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/LakeSoulMultiTablesSink.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/bucket/DefaultOneTableBulkFormatBuilder.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/LakeSoulLookupTableSource.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/LakeSoulSource.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/table/LakeSoulTableSource.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/tool/JobOptions.java

1 support lineage for kafka、lakesoul datastream source to sink into lakesoul
2 suppport lineage for laksoul datastream source to sink to doris、lakesoul and kafka
3 support lineage for flinl sql submit
4 support yarn and k8s application mode
Close #167

[Flink] Integrate open lineage
