lakesoul-io/LakeSoul

src/main/scala/com/dmetasoul/lakesoul/sql/LakeSoulSparkSessionExtension.scala
src/main/scala/org/apache/spark/sql/lakesoul/LakeSoulUtils.scala
src/main/scala/org/apache/spark/sql/lakesoul/rules/ProcessCDCTableMergeOnRead.scala
src/test/scala/org/apache/spark/sql/lakesoul/TestCDC.scala
src/test/scala/org/apache/spark/sql/lakesoul/test/LakeSQLCommandSoulTest.scala

1.  LakeSoulSparkSession inject
2.  add logicalplan ProcessCDCTableMergeOnRead
3.  add TestCDC

Cdc support v2

---

src/main/scala/org/apache/spark/sql/lakesoul/commands/CreateTableCommand.scala
src/test/scala/org/apache/spark/sql/lakesoul/TableCreationTests.scala

1. Support create hash partitioned table by sql with table properties;
2. Add test case;

support create hash partitioned table by sql

---

src/main/scala/org/apache/spark/sql/execution/datasources/v2/merge/MergeParquetScan.scala
src/main/scala/org/apache/spark/sql/lakesoul/LakeSoulUtils.scala
src/test/scala/org/apache/spark/sql/lakesoul/CDCSuite.scala

remove cdc filter from mergescan

remove cdc filter from mergescan

---

.gitattributes
README-CN.md
README.md
examples/cdc_ingestion_debezium/MysqlBenchmark/MysqlCdcBenchmark.sh
examples/cdc_ingestion_debezium/MysqlBenchmark/mysql_random_data_insert
examples/cdc_ingestion_debezium/MysqlBenchmark/mysqlcdc.conf
examples/cdc_ingestion_debezium/README.md

1. Add an e2e example on how to setup a CDC sink from MySQL to LakeSoul with Debezium and Kafka, together with MySQL data generator.
Closes #15 #16

add a cdc sink example

---

src/main/java/org/apache/flink/lakeSoul/sink/LakesSoulAbstractStreamingWriter.java
src/main/java/org/apache/flink/lakeSoul/sink/MetaDataCommit.java
src/test/java/org/apache/flink/lakeSoul/test/Main.java

support exactly once semantics for flink write

---

src/main/scala/org/apache/spark/sql/lakesoul/rules/ProcessCDCTableMergeOnRead.scala

fix filter bug when cdc column is not used

fix filter bug when cdc column is not used

---

src/main/java/org/apache/flink/lakeSoul/sink/LakSoulFileWriter.java
src/main/java/org/apache/flink/lakeSoul/sink/MetaDataCommit.java
src/main/java/org/apache/flink/lakeSoul/sink/bucket/LakeSoulBucket.java
src/main/java/org/apache/flink/lakeSoul/sink/partition/CdcPartitionComputer.java
src/main/java/org/apache/flink/lakeSoul/sink/partition/DataPartitioner.java
src/main/java/org/apache/flink/lakeSoul/table/LakeSoulTableSink.java
src/main/java/org/apache/flink/lakeSoul/tool/FlinkUtil.java
src/main/java/org/apache/flink/lakeSoul/tool/LakeSoulKeyGen.java
src/main/java/org/apache/flink/lakeSoul/tool/RowDataProjection.java
src/main/scala/com/dmetasoul/lakesoul/meta/DataTypeUtil.scala

Align hash bucket and sort logic in flink with spark #60

---

lakesoul-spark/src/main/scala/org/apache/spark/sql/execution/datasources/v2/merge/parquet/batch/merge_operator/MergeOperator.scala

add MergeNonNullOp or merge operator

add MergeNonNullOp for merge operator

---

docker/lakesoul-docker-compose-env/docker-compose.yml
lakesoul-common/pom.xml
lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/DBUtil.java
lakesoul-flink/pom.xml
lakesoul-flink/src/main/java/org/apache/flink/lakeSoul/sink/LakSoulFileWriter.java
lakesoul-flink/src/main/java/org/apache/flink/lakeSoul/sink/LakesSoulAbstractStreamingWriter.java
lakesoul-flink/src/main/java/org/apache/flink/lakeSoul/sink/bucket/LakeSoulBucket.java
lakesoul-flink/src/main/java/org/apache/flink/lakeSoul/sink/bucket/LakeSoulCDCComparator.java
lakesoul-flink/src/main/java/org/apache/flink/lakeSoul/sink/bucket/LakeSoulCDCElement.java
lakesoul-flink/src/main/java/org/apache/flink/lakeSoul/sink/partition/DataPartitioner.java
lakesoul-flink/src/main/java/org/apache/flink/lakeSoul/table/LakeSoulTableSink.java
lakesoul-flink/src/main/java/org/apache/flink/lakeSoul/tool/LakeSoulKeyGen.java
lakesoul-flink/src/test/java/org/apache/flink/lakeSoul/test/LakeSoulFileSinkTest.java
lakesoul-flink/src/test/java/org/apache/flink/lakeSoul/test/Main.java
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/SnapshotManagement.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/sources/LakeSoulSQLConf.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/utils/AnalysisHelper.scala
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/test/HiveTest.scala
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/test/LakeSoulSQLCommandTest.scala

Fix flink cdc write event order

---

lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/MysqlCdc.java

flink cdc task add argument serverTimeZone

flink cdc task add argument serverTimeZone

---

lakesoul-common/pom.xml
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/MysqlCdc.java
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/SnapshotManagement.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/sources/LakeSoulSQLConf.scala

[BUG] fix pg password auth failed exception

---

lakesoul-spark/pom.xml

solve building problem of  confluent jar can't download

solve dependency problem of confluent jar

---

lakesoul-spark/src/main/java/org/apache/spark/sql/execution/datasources/parquet/NativeVectorizedReader.java
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/sources/LakeSoulSQLConf.scala
native-io/lakesoul-io-c/src/lib.rs
native-io/lakesoul-io-java/src/main/java/org/apache/arrow/lakesoul/io/NativeIOWrapper.java
native-io/lakesoul-io-java/src/main/java/org/apache/arrow/lakesoul/io/jnr/LibLakeSoulIO.java
native-io/lakesoul-io/Cargo.toml
native-io/lakesoul-io/src/filter/parser.rs
native-io/lakesoul-io/src/lakesoul_io_config.rs
native-io/lakesoul-io/src/lakesoul_reader.rs
native-io/lakesoul-io/src/lakesoul_writer.rs
native-io/lakesoul-io/src/lib.rs

1. Initial async writer implementation.
2. Refactor native io configs to share config options between reader and writer.
Fixes #127

[NativeIO] Native io parquet writer implementation

---

lakesoul-flink/pom.xml
native-io/lakesoul-io-c/src/lib.rs
native-io/lakesoul-io-java/src/main/java/org/apache/arrow/lakesoul/io/NativeIOWriter.java
native-io/lakesoul-io-java/src/main/java/org/apache/arrow/lakesoul/io/jnr/LibLakeSoulIO.java
native-io/lakesoul-io-java/src/test/scala/test/org/apache/arrow/lakesoul/TestLakeSoulNativeReaderWriter.scala
native-io/lakesoul-io/Cargo.toml
native-io/lakesoul-io/src/lakesoul_io_config.rs
native-io/lakesoul-io/src/lakesoul_writer.rs

[NativeIO] Native writer with primary keys sort support

---

.github/workflows/flink-cdc-test.yml
.github/workflows/maven-test.yml
native-io/Cargo.lock
native-io/lakesoul-io-c/Cargo.toml
native-io/lakesoul-io-java/src/main/java/org/apache/arrow/lakesoul/io/jnr/JnrLoader.java
native-io/lakesoul-io/Cargo.toml

[NativeIO] upgrade arrow-rs to 31 and datafusion to 17

---

lakesoul-flink/pom.xml
lakesoul-spark/pom.xml
lakesoul-spark/src/main/java/org/apache/spark/sql/execution/datasources/parquet/NativeVectorizedReader.java
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/benchmark/io/ParquetScanBenchmark.scala
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/benchmark/io/README.md
native-io/Cargo.lock
native-io/lakesoul-io-java/pom.xml
native-io/lakesoul-io-java/src/main/java/org/apache/arrow/lakesoul/io/NativeIOBase.java

[NativeIO][Spark] Package native lib in lakesoul-spark jar

---

.github/workflows/flink-cdc-test.yml
.github/workflows/maven-test.yml
lakesoul-flink/pom.xml
lakesoul-spark/pom.xml
native-io/lakesoul-io-java/pom.xml

[NativeIO] use maven profile for native packaging. default to local native build

---

lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/benchmark/io/MorReadBenchmark.scala
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/benchmark/io/README.md
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/benchmark/io/UpsertWriteBenchmark.scala
native-io/Cargo.lock
native-io/lakesoul-io/Cargo.toml
native-io/lakesoul-io/src/lakesoul_io_config.rs
native-io/lakesoul-io/src/sorted_merge/combiner.rs
native-io/lakesoul-io/src/sorted_merge/merge_operator.rs
native-io/lakesoul-io/src/sorted_merge/sort_key_range.rs
native-io/lakesoul-io/src/sorted_merge/sorted_stream_merger.rs

[NativeIO] optimize with smallvec for native merge

---

lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/writer/NativeParquetWriter.java

[NativeIO][Flink] fix flink writer batch reset in java before write

---

lakesoul-spark/src/main/java/org/apache/spark/sql/execution/datasources/parquet/NativeVectorizedReader.java
lakesoul-spark/src/main/scala/org/apache/spark/sql/execution/datasources/v2/merge/parquet/Native/NativeMergeFilePartitionReaderFactory.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/execution/datasources/v2/merge/parquet/Native/NativeMergeParquetPartitionReaderFactory.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/rules/SetPartitionAndOrdering.scala
native-io/lakesoul-io-java/src/main/java/org/apache/arrow/lakesoul/io/NativeIOBase.java
native-io/lakesoul-io-java/src/main/scala/org/apache/arrow/lakesoul/io/read/LakeSoulArrowReader.scala

fix memory leak. add columnar supports

---

lakesoul-flink/pom.xml

[Flink] pack paranamer to flink release jar

---

native-io/Cargo.lock
native-io/lakesoul-io/Cargo.toml
native-io/lakesoul-io/src/lib.rs

[NativeIO] use tcmalloc as global allocator

---

native-io/lakesoul-io-c/src/lib.rs
native-io/lakesoul-io-java/src/main/java/com/dmetasoul/lakesoul/lakesoul/io/NativeIOReader.java
native-io/lakesoul-io-java/src/main/scala/com/dmetasoul/lakesoul/LakeSoulArrowReader.scala
native-io/lakesoul-io/src/lakesoul_reader.rs

[NativeIO] fix memory leak in native reader

---

lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/LakeSoulDDLSink.java

[Flink] avoid cast global parameter to ParameterTool

---

native-io/Cargo.lock
native-io/lakesoul-io-c/Cargo.toml
native-io/lakesoul-io/Cargo.toml

migrate arrow-rs and datafusion deps to new org

---

lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/LakeSoulOneSplitRecordsReader.java
lakesoul-flink/src/main/java/org/apache/flink/table/runtime/arrow/vectors/ArrowTimestampColumnVector.java
lakesoul-flink/src/main/scala/com/dmetasoul/lakesoul/meta/DataTypeUtil.scala
lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/LakeSoulSourceTest.java

1.fix the mismatched conversion of data type timestamp with time zone and ValueVector in flink
2.add unit test about incremental read and snapshot read
Close #216

fix data type timestamp with zone

---

native-io/lakesoul-io-java/src/main/scala/com/dmetasoul/lakesoul/LakeSoulArrowReader.scala

Throw execption when LakeSoulArrowReader.hasNext
Part of #218

[NativeIO]throw execption when LakeSoulArrowReader.hasNext

---

lakesoul-flink/pom.xml
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/sql/SubmitMain.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/sql/Submitter.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/sql/SubmitterFactory.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/sql/common/FlinkOption.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/sql/common/JobType.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/sql/common/LanguageType.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/sql/common/SubmitOption.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/sql/common/SubmitType.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/sql/flink/Configurations.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/sql/flink/ExecuteSql.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/sql/flink/FlinkSqlSubmitter.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/sql/utils/SqlSplitter.java
lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/SubmitMainTest.java

Flink sql application submitter 
Close #199

add flink sql submitter(#199)

---

lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/sql/common/JobType.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/sql/flink/FlinkSqlSubmitter.java

add batch in flink sql submitter

[Flink]add batch in flink sql submitter

---

.github/workflows/maven-test.yml
lakesoul-spark/pom.xml

1. Prepare meta db(init or clean) before maven test
2. Upload test report site as artifact

Prepare meta in maven test

---

lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/MysqlCdc.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/types/BinarySourceRecord.java

1. change MysqlCdc sort-key generation way；
2. remove Initialize table creation before task start.

Modify mysqlcdc sort key generation way

---

lakesoul-flink/src/main/java/org/apache/flink/lakesoul/types/BinarySourceRecord.java

format tablePath with hadoop configuration

format table path with hdfs configuration

---

README.md
lakesoul-flink/pom.xml
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/metadata/LakeSoulCatalog.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/bucket/CdcPartitionComputer.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/state/LakeSoulSinkGlobalCommittableSerializer.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/LakeSoulDynamicSplitEnumerator.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/LakeSoulLookupTableSource.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/LakeSoulOneSplitRecordsReader.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/LakeSoulSource.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/LakeSoulSplitReader.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/ParquetFilters.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/table/LakeSoulTableSource.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/types/BinarySourceRecord.java
lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/flinkSource/BatchReadSuite.java
lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/flinkSource/TestUtils.java
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/TableCreationTests.scala
native-io/Cargo.lock
native-io/lakesoul-io/Cargo.toml
native-io/lakesoul-io/src/default_column_stream/mod.rs
native-io/lakesoul-io/src/lakesoul_io_config.rs
native-io/lakesoul-io/src/lakesoul_reader.rs
native-io/lakesoul-io/src/lakesoul_writer.rs
native-io/lakesoul-io/src/transform.rs

[Flink] implement filter pushdown and fix partition pushdown in flink

---

.github/workflows/flink-cdc-test.yml
.gitignore
lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/fail/LakeSoulSinkFailTest.java
native-io/Cargo.lock
native-io/lakesoul-io-c/Cargo.toml
native-io/lakesoul-io-c/build.rs

Generate a C header file using cbindgen.

[Python][NativeIO] Add C interface definition

---

lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/DBConnector.java
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/commands/UpdateSuiteBase.scala
native-io/lakesoul-io/src/lakesoul_io_config.rs
website/docs/03-Usage Docs/01-setup-meta-env.md
website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/01-setup-meta-env.md

1. Update arrow version to fix is_null filter bug;
2. Improve docs when meta connection fails.

[NativeIO] update arrow version

---

lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/GlobalConfig.java
lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/rbac/AuthZAfter.java
lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/rbac/AuthZBefore.java
lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/rbac/AuthZEnforcer.java
lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/rbac/fetcher/AuthZFetcher.java
lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/rbac/fetcher/AuthZIdentFetcher.java
lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/rbac/fetcher/AuthZNullFetcher.java
lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/rbac/fetcher/AuthZParamFetcher.java
lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/rbac/fetcher/TableReadFetcher.java
lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/rbac/fetcher/TableWriteFetcher.java
lakesoul-flink/src/test/java/com/dmetasoul/lakesoul/meta/LakeSoulRBACTest.java
lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/AbstractTestBase.java
lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/DebugMain.java
lakesoul-spark/src/test/scala/com/dmetasoul/lakesoul/meta/RBACOperatinSuite.scala

change old license to the new one

fix apache license

---

website/docs/01-Getting Started/01-setup-local-env.md
website/docs/03-Usage Docs/02-setup-spark.md
website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/01-Getting Started/01-setup-local-env.md
website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/02-setup-spark.md

Refine docs about preparing flink env

[Docs] update docs

---

lakesoul-flink/pom.xml

[Flink] upgrade flink cdc connector to 2.4

---

python/examples/README.md
python/examples/food101/README.md
python/examples/food101/embedding.py
python/examples/food101/import_data.py
python/examples/food101/search.py
python/examples/imdb/README.md
python/examples/imdb/accuracy/accuracy.py
python/examples/imdb/import_data.py
python/examples/imdb/inference.py
python/examples/imdb/train.py
python/examples/import_titanic.py
python/examples/lakesoul-docker-compose-env/docker-compose.yml
python/examples/lakesoul-docker-compose-env/meta_cleanup.sql
python/examples/lakesoul-docker-compose-env/meta_init.sql
python/examples/lakesoul-docker-compose-env/mysql_init.sql
python/examples/lakesoul.properties
python/examples/lakesoul_env.sh
python/examples/requirements.txt
python/examples/titanic/README.md
python/examples/titanic/feature_transform.py
python/examples/titanic/import_data.py
python/examples/titanic/train.py

[Python] Examples using Python API for AI model training

---

lakesoul-spark/src/main/scala/org/apache/spark/sql/execution/datasources/v2/merge/MergeParquetScan.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/execution/datasources/v2/merge/parquet/Native/NativeMergeParquetPartitionReaderFactory.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/catalog/LakeSoulScanBuilder.scala
lakesoul-spark/src/test/scala/org/apache/spark/sql/execution/datasource/parquet/ParquetNativeFilterSuite.scala
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/CDCSuite.scala
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/commands/UpsertSuiteBase.scala
rust/lakesoul-io/src/datasource/parquet_source.rs
rust/lakesoul-io/src/filter/parser.rs
rust/lakesoul-io/src/lakesoul_io_config.rs
rust/lakesoul-io/src/sorted_merge/combiner.rs

[Spark]Spark parquet filter pushdown exactly

---

pyproject.toml
python/lakesoul/huggingface/from_lakesoul.py
python/lakesoul/ray/__init__.py
python/lakesoul/ray/read_lakesoul.py

Part #201 
Add Ray Dataset interface for reading LakeSoul data in Ray.

[Python][Dataset] Add Ray reading support

---

lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/DBManager.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/metadata/LakeSoulCatalog.java
lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/flinkSource/DDLSuite.java
lakesoul-spark/src/main/scala/com/dmetasoul/lakesoul/meta/SparkMetaVersion.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/catalog/LakeSoulTableV2.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/rules/LakeSoulUnsupportedOperationsCheck.scala
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/NotSupportedDDLSuite.scala
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/SQLDropPartitionSuite.scala
rust/lakesoul-metadata/src/lib.rs

spark sql support 'drop partition' operation

[Spark] Spark Sql Support 'drop partition' Operation

---

pyproject.toml
python/docker_build_all_wheels.py
python/lakesoul/metadata/native_client.py
python/lakesoul/metadata/utils.py

1. Fix LakeSoul wheel building related problems.
2. Update LakeSoul wheel version from 1.0.0b0 to 1.0.0b1.

[Python] Fix wheel building; update version to 1.0.0b1

---

rust/Cargo.lock
rust/lakesoul-datafusion/Cargo.toml
rust/lakesoul-datafusion/src/test/upsert_tests.rs

Add rust test functions to examine upsert feature

Add some rust test cases

---

rust/lakesoul-datafusion/src/test/upsert_tests.rs

fix test cases in mod  upsert_with_io_config_tests, and add test cases in mod upsert_with_metadata_tests

[Rust] add upsert test cases

---

rust/lakesoul-datafusion/src/test/upsert_tests.rs
rust/lakesoul-io/src/lakesoul_io_config.rs

add sort feature and refine test cases in upsert_test.rs

refine upsert test

---

lakesoul-flink/pom.xml
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/OracleCdc.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/SyncDatabase.java
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/tool/LakeSoulSinkDatabasesOptions.java

pg and mysql now can support base data type,and batch out the lake or stream out the lake is OK.next will perfect the process of leaving the lake to doris

[Flink] Add export to external dbs for LakeSoul's tables

---

lakesoul-spark/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/LakeSoulSparkSqlExtensionsParser.scala
website/docs/01-Getting Started/02-spark-guide.mdx
website/docs/02-Tutorials/03-snapshot-manage.md
website/docs/03-Usage Docs/03-spark-api-docs.md
website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/01-Getting Started/02-spark-guide.mdx
website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/02-Tutorials/03-snapshot-manage.md
website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/03-spark-api-docs.md

2. add call syntax for rollback and compaction in snapshot-manage.md and spark-api-docs.md

[Docs] add pyspark in spark-guide

---

lakesoul-flink/pom.xml
lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/JdbcCDC.java

Support sqlserver CDC

---

rust/lakesoul-io/src/lakesoul_io_config.rs

To optimize table with very large column num (over 10k), some rules in datafusion are very slow.
For LakeSoul, we only need pushdown rules for reader to work.

[Rust] Keep only push down rules in datafusion

---

lakesoul-common/pom.xml
lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/jnr/LibLakeSoulMetaData.java
lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/jnr/NativeMetadataJavaClient.java
lakesoul-common/src/test/java/com/dmetasoul/lakesoul/meta/jnr/SubstraitTest.java
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/SplitDescSuite.scala
rust/Cargo.lock
rust/Cargo.toml
rust/lakesoul-metadata-c/src/lib.rs
rust/lakesoul-metadata/Cargo.toml
rust/lakesoul-metadata/src/error.rs
rust/lakesoul-metadata/src/metadata_client.rs
rust/lakesoul-metadata/src/transfusion.rs

previous implementation may lead concurrency issue

[Rust] (metadata) move metadataclient to rawclient

---

lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/DBUtil.java
native-io/lakesoul-io-java/pom.xml

1、change DBUtil from private to public to get pg info for doris catalog
2、add some packages to lakesoul-io for doris

[NativeIO] Shade packages into lakesoul-io-java

---

lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/SyncDatabase.java

[Flink] Support other options for external database export

---

.github/workflows/maven-test.yml
lakesoul-spark/src/main/scala/org/apache/spark/sql/execution/datasources/LakeSoulFileWriter.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/execution/datasources/v2/merge/MergeParquetScan.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/execution/datasources/v2/parquet/NativeParquetFileFormat.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/execution/datasources/v2/parquet/NativeParquetOutputWriter.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/DelayedCommitProtocol.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/DelayedCopyCommitProtocol.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/TransactionalWrite.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/commands/CompactionCommand.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/sources/LakeSoulSQLConf.scala
lakesoul-spark/src/main/scala/org/apache/spark/sql/vectorized/NativeIOUtils.scala
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/SplitDescSuite.scala
lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/commands/CompactionSuite.scala
native-io/lakesoul-io-java/src/main/java/com/dmetasoul/lakesoul/lakesoul/io/NativeIOWriter.java
rust/Cargo.lock
rust/lakesoul-io/Cargo.toml
rust/lakesoul-io/examples/profiling_merge.rs
rust/lakesoul-io/src/async_writer/multipart_writer.rs
rust/lakesoul-io/src/constant.rs
rust/lakesoul-io/src/lakesoul_io_config.rs
rust/lakesoul-io/src/lakesoul_reader.rs
rust/lakesoul-io/src/lakesoul_writer.rs
rust/lakesoul-io/src/sorted_merge/combiner.rs
rust/lakesoul-io/src/sorted_merge/sort_key_range.rs
rust/lakesoul-io/src/sorted_merge/sorted_stream_merger.rs

Improved merge on read performance by 2x

[NativeIO]Add UseLastRangeCombiner for default usage of merge on read

---

lakesoul-presto/pom.xml
lakesoul-presto/src/main/java/com/facebook/presto/lakesoul/handle/LakeSoulTableLayoutHandle.java

[Presto] To fit with velox, add a field to pushdown filter.

[Presto] add field to adapt to velox

---

website/docs/03-Usage Docs/08-auto-compaction-task.md
website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/08-auto-compaction-task.md

[Docs] Update Compaction Operation Docs
